export const cities = [
  { label: "Água Branca", value: "Água Branca" },
  { label: "Anadia", value: "Anadia" },
  { label: "Arapiraca", value: "Arapiraca" },
  { label: "Atalaia", value: "Atalaia" },
  { label: "Barra de Santo Antônio", value: "Barra de Santo Antônio" },
  { label: "Barra de São Miguel", value: "Barra de São Miguel" },
  { label: "Batalha", value: "Batalha" },
  { label: "Belém", value: "Belém" },
  { label: "Belo Monte", value: "Belo Monte" },
  { label: "Boca da Mata", value: "Boca da Mata" },
  { label: "Branquinha", value: "Branquinha" },
  { label: "Cacimbinhas", value: "Cacimbinhas" },
  { label: "Cajueiro", value: "Cajueiro" },
  { label: "Campestre", value: "Campestre" },
  { label: "Campo Alegre", value: "Campo Alegre" },
  { label: "Campo Grande", value: "Campo Grande" },
  { label: "Canapi", value: "Canapi" },
  { label: "Capela", value: "Capela" },
  { label: "Carneiros", value: "Carneiros" },
  { label: "Chã Preta", value: "Chã Preta" },
  { label: "Coité do Nóia", value: "Coité do Nóia" },
  { label: "Colônia Leopoldina", value: "Colônia Leopoldina" },
  { label: "Coqueiro Seco", value: "Coqueiro Seco" },
  { label: "Coruripe", value: "Coruripe" },
  { label: "Craíbas", value: "Craíbas" },
  { label: "Delmiro Gouveia", value: "Delmiro Gouveia" },
  { label: "Dois Riachos", value: "Dois Riachos" },
  { label: "Estrela de Alagoas", value: "Estrela de Alagoas" },
  { label: "Feira Grande", value: "Feira Grande" },
  { label: "Feliz Deserto", value: "Feliz Deserto" },
  { label: "Flexeiras", value: "Flexeiras" },
  { label: "Girau do Ponciano", value: "Girau do Ponciano" },
  { label: "Ibateguara", value: "Ibateguara" },
  { label: "Igaci", value: "Igaci" },
  { label: "Igreja Nova", value: "Igreja Nova" },
  { label: "Inhapi", value: "Inhapi" },
  { label: "Jacaré dos Homens", value: "Jacaré dos Homens" },
  { label: "Jacuípe", value: "Jacuípe" },
  { label: "Japaratinga", value: "Japaratinga" },
  { label: "Jaramataia", value: "Jaramataia" },
  { label: "Jequiá da Praia", value: "Jequiá da Praia" },
  { label: "Joaquim Gomes", value: "Joaquim Gomes" },
  { label: "Jundiá", value: "Jundiá" },
  { label: "Junqueiro", value: "Junqueiro" },
  { label: "Lagoa da Canoa", value: "Lagoa da Canoa" },
  { label: "Limoeiro de Anadia", value: "Limoeiro de Anadia" },
  { label: "Maceió", value: "Maceió" },
  { label: "Major Isidoro", value: "Major Isidoro" },
  { label: "Mar Vermelho", value: "Mar Vermelho" },
  { label: "Maragogi", value: "Maragogi" },
  { label: "Maravilha", value: "Maravilha" },
  { label: "Marechal Deodoro", value: "Marechal Deodoro" },
  { label: "Maribondo", value: "Maribondo" },
  { label: "Mata Grande", value: "Mata Grande" },
  { label: "Matriz de Camaragibe", value: "Matriz de Camaragibe" },
  { label: "Messias", value: "Messias" },
  { label: "Minador do Negrão", value: "Minador do Negrão" },
  { label: "Monteirópolis", value: "Monteirópolis" },
  { label: "Murici", value: "Murici" },
  { label: "Novo Lino", value: "Novo Lino" },
  { label: "Olho d'Água das Flores", value: "Olho d'Água das Flores" },
  { label: "Olho d'Água do Casado", value: "Olho d'Água do Casado" },
  { label: "Olho d'Água Grande", value: "Olho d'Água Grande" },
  { label: "Olivença", value: "Olivença" },
  { label: "Ouro Branco", value: "Ouro Branco" },
  { label: "Palestina", value: "Palestina" },
  { label: "Palmeira dos Índios", value: "Palmeira dos Índios" },
  { label: "Pão de Açúcar", value: "Pão de Açúcar" },
  { label: "Pariconha", value: "Pariconha" },
  { label: "Paripueira", value: "Paripueira" },
  { label: "Passo de Camaragibe", value: "Passo de Camaragibe" },
  { label: "Paulo Jacinto", value: "Paulo Jacinto" },
  { label: "Penedo", value: "Penedo" },
  { label: "Piaçabuçu", value: "Piaçabuçu" },
  { label: "Pilar", value: "Pilar" },
  { label: "Pindoba", value: "Pindoba" },
  { label: "Piranhas", value: "Piranhas" },
  { label: "Poço das Trincheiras", value: "Poço das Trincheiras" },
  { label: "Porto Calvo", value: "Porto Calvo" },
  { label: "Porto de Pedras", value: "Porto de Pedras" },
  { label: "Porto Real do Colégio", value: "Porto Real do Colégio" },
  { label: "Quebrangulo", value: "Quebrangulo" },
  { label: "Rio Largo", value: "Rio Largo" },
  { label: "Roteiro", value: "Roteiro" },
  { label: "Santa Luzia do Norte", value: "Santa Luzia do Norte" },
  { label: "Santana do Ipanema", value: "Santana do Ipanema" },
  { label: "Santana do Mundaú", value: "Santana do Mundaú" },
  { label: "São Brás", value: "São Brás" },
  { label: "São José da Laje", value: "São José da Laje" },
  { label: "São José da Tapera", value: "São José da Tapera" },
  { label: "São Luís do Quitunde", value: "São Luís do Quitunde" },
  { label: "São Miguel dos Campos", value: "São Miguel dos Campos" },
  { label: "São Miguel dos Milagres", value: "São Miguel dos Milagres" },
  { label: "São Sebastião", value: "São Sebastião" },
  { label: "Satuba", value: "Satuba" },
  { label: "Senador Rui Palmeira", value: "Senador Rui Palmeira" },
  { label: "Tanque d'Arca", value: "Tanque d'Arca" },
  { label: "Taquarana", value: "Taquarana" },
  { label: "Teotônio Vilela", value: "Teotônio Vilela" },
  { label: "Traipu", value: "Traipu" },
  { label: "União dos Palmares", value: "União dos Palmares" },
  { label: "Viçosa", value: "Viçosa" },
];

export const medicalSpecialties = [
  { label: "Acupuntura", value: "Acupuntura" },
  { label: "Alergia e Imunologia", value: "Alergia e Imunologia" },
  { label: "Anestesiologia", value: "Anestesiologia" },
  { label: "Angiologia", value: "Angiologia" },
  { label: "Cardiologia", value: "Cardiologia" },
  { label: "Cirurgia Cardiovascular", value: "Cirurgia Cardiovascular" },
  { label: "Cirurgia da Mão", value: "Cirurgia da Mão" },
  {
    label: "Cirurgia de Cabeça e Pescoço",
    value: "Cirurgia de Cabeça e Pescoço",
  },
  {
    label: "Cirurgia do Aparelho Digestivo",
    value: "Cirurgia do Aparelho Digestivo",
  },
  { label: "Cirurgia Geral", value: "Cirurgia Geral" },
  { label: "Cirurgia Oncológica", value: "Cirurgia Oncológica" },
  { label: "Cirurgia Pediátrica", value: "Cirurgia Pediátrica" },
  { label: "Cirurgia Plástica", value: "Cirurgia Plástica" },
  { label: "Cirurgia Torácica", value: "Cirurgia Torácica" },
  { label: "Cirurgia Vascular", value: "Cirurgia Vascular" },
  { label: "Clínica Médica", value: "Clínica Médica" },
  { label: "Coloproctologia", value: "Coloproctologia" },
  { label: "Dermatologia", value: "Dermatologia" },
  {
    label: "Endocrinologia e Metabologia",
    value: "Endocrinologia e Metabologia",
  },
  { label: "Endoscopia", value: "Endoscopia" },
  { label: "Gastroenterologia", value: "Gastroenterologia" },
  { label: "Genética Médica", value: "Genética Médica" },
  { label: "Geriatria", value: "Geriatria" },
  { label: "Ginecologia e Obstetrícia", value: "Ginecologia e Obstetrícia" },
  { label: "Hematologia e Hemoterapia", value: "Hematologia e Hemoterapia" },
  { label: "Homeopatia", value: "Homeopatia" },
  { label: "Infectologia", value: "Infectologia" },
  { label: "Mastologia", value: "Mastologia" },
  { label: "Medicina de Emergência", value: "Medicina de Emergência" },
  {
    label: "Medicina de Família e Comunidade",
    value: "Medicina de Família e Comunidade",
  },
  { label: "Medicina de Tráfego", value: "Medicina de Tráfego" },
  { label: "Medicina do Trabalho", value: "Medicina do Trabalho" },
  { label: "Medicina Esportiva", value: "Medicina Esportiva" },
  {
    label: "Medicina Física e Reabilitação",
    value: "Medicina Física e Reabilitação",
  },
  { label: "Medicina Intensiva", value: "Medicina Intensiva" },
  {
    label: "Medicina Legal e Perícia Médica",
    value: "Medicina Legal e Perícia Médica",
  },
  { label: "Medicina Nuclear", value: "Medicina Nuclear" },
  {
    label: "Medicina Preventiva e Social",
    value: "Medicina Preventiva e Social",
  },
  { label: "Nefrologia", value: "Nefrologia" },
  { label: "Neurocirurgia", value: "Neurocirurgia" },
  { label: "Neurologia", value: "Neurologia" },
  { label: "Nutrologia", value: "Nutrologia" },
  { label: "Oftalmologia", value: "Oftalmologia" },
  { label: "Oncologia Clínica", value: "Oncologia Clínica" },
  { label: "Ortopedia e Traumatologia", value: "Ortopedia e Traumatologia" },
  { label: "Otorrinolaringologia", value: "Otorrinolaringologia" },
  { label: "Patologia", value: "Patologia" },
  {
    label: "Patologia Clínica/Medicina Laboratorial",
    value: "Patologia Clínica/Medicina Laboratorial",
  },
  { label: "Pediatria", value: "Pediatria" },
  { label: "Pneumologia", value: "Pneumologia" },
  { label: "Psiquiatria", value: "Psiquiatria" },
  {
    label: "Radiologia e Diagnóstico por Imagem",
    value: "Radiologia e Diagnóstico por Imagem",
  },
  { label: "Radioterapia", value: "Radioterapia" },
  { label: "Reumatologia", value: "Reumatologia" },
  { label: "Urologia", value: "Urologia" },
];

export const situations = [
  { label: "Recém Formado", value: "Recém Formado" },
  { label: "Residente", value: "Residente" },
  { label: "Médico", value: "Médico" },
];
